image: ubuntu:focal

matrix:
  -
    env: SCRIPT=test NODE_VERSION=15

before_install:
  - apt update && apt install -y wget
  - wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
  - nvm install $NODE_VERSION
  - npm i -g yarn

install:
  - yarn install

script:
  - if [[ "$SCRIPT" ]]; then CI=true yarn run $SCRIPT -- --watchAll=false; fi
  - yarn run build

cache:
  - node_modules
